name: 알고리즘 문제풀이 기록

on:
  schedule:
    - cron: '0 22 * * *' #매일 오후 10시 커밋
  push:
    branches: [ main ]
  paths:
    - "Algorithm"

jobs:
  Make-a-Record:
    name: "알고리즘 문제풀이 기록"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "./Algorithm"
    steps:
      - name: set Today Date
        run: echo TODAY_DATE=$(date+%Y년\ %m월\ %d일) >> $GITHUB_ENV
        
      - name: echo repository name
        run: echo "${{ github.repository }}"

      - name: repository checkout
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}
          token: ${{ secrets.MY_GITHUB_TOKEN }}

      - name: Add date and push
        run: |
          git add .
          git config --global user.email "github-@github.com"
          git config --global user.name "github-actions"
          git commit -m "${{ env.TODAY_DATE }}"
          git push
